env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy

snapshot:
  name_template: "{{ .Version }}-next"

#gomod:
#  proxy: true

report_sizes: true

builds:
  - main: ./cmd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X "github.com/starudream/go-lib/constant.VERSION=v{{ .Version }}"
      - -X "github.com/starudream/go-lib/constant.BIDTIME={{ .Date }}"
      - -X "github.com/starudream/go-lib/constant.NAME="
      - -X "github.com/starudream/go-lib/constant.PREFIX="

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

release:
  draft: true
  replace_existing_draft: true
  target_commitish: "{{ .Commit }}"

changelog:
  sort: asc
  use: github
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 10
    - title: Bug fixes
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 20
    - title: Performance improvements
      regexp: "^.*perf[(\\w)]*:+.*$"
      order: 30
    - title: Others
      order: 99
